# Generated by Django 5.2.12 on 2026-03-26 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0005_savedrecipe"),
    ]

    operations = [
        migrations.AddField(
            model_name="recipes",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="recipe_images/"),
        ),
    ]
